//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commandes
    {
        public int id_commande { get; set; }
        public Nullable<int> Idplat { get; set; }
        public Nullable<int> QTT { get; set; }
        public string etat_plat { get; set; }
        public string etat_comm { get; set; }
        public Nullable<int> Id_table { get; set; }
    
        public virtual Plats Plats { get; set; }
        public virtual Tables Tables { get; set; }
    }
}
