//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Serveur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Serveur()
        {
            this.Tables = new HashSet<Tables>();
            this.TotalCommandes = new HashSet<TotalCommandes>();
        }
    
        public int id_serveur { get; set; }
        public string nom { get; set; }
        [Required(ErrorMessage = "Entrez votre login", AllowEmptyStrings = false)]
        public string login { get; set; }
        [Required(ErrorMessage = "Entrez votre mot de passe", AllowEmptyStrings = false)]
        [DataType(DataType.Password)]
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tables> Tables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TotalCommandes> TotalCommandes { get; set; }
    }
}
